DROP TABLE IF EXISTS challengesubmissions RESTRICT;

DROP TABLE IF EXISTS challenges RESTRICT;

DROP TABLE IF EXISTS challengelanguages RESTRICT;

DROP TABLE IF EXISTS userroles RESTRICT;

DROP TABLE IF EXISTS roles RESTRICT;

DROP TABLE IF EXISTS assets RESTRICT;

DROP TABLE IF EXISTS files RESTRICT;

DROP TABLE IF EXISTS tokens RESTRICT;

DROP TABLE IF EXISTS users RESTRICT;

DROP SEQUENCE IF EXISTS global_snowflake_id_seq;

DROP FUNCTION IF EXISTS create_snowflake();

DROP FUNCTION IF EXISTS snowflake_to_timestamp(flake BIGINT);
